### ISSUE TITLE
Timing doesn't work

### ISSUE THREAD

**Issue by Spontini** [Minecolonies/Rankup#13]
Minecraft: 1.12.2
Sponge: 1.12.2-2611-7.1.0-BETA-2990
Modpack: FTB Revelation Update 1.8
Plugin: Rankup-V7795-API7

Issue: Timings doesn't work, people playing for hours but their play time stuck in 1 minutes or two and that's why plugin does not work.

Configs:
rankup.conf: https://pastebin.com/c9cv9HNi
groups.conf: https://pastebin.com/h9Fy21SQ

**Comment by Asherslab** [comment]
@Explosivee i take it you edited your `databases` section of your rankup.conf with the correct details? otherwise no, timing won't work

**Comment by Spontini** [comment]
Okay, i just installed Apache, MySQL and PHP (not php MyAdmin) then i create a database named "rankup" then i change my config as
databases {
    # You may choose between MySQL (Mariadb works too) or H2 (Hikari) databases for Player Stats storage!
    database=rankup
    sqlAddress="MYIP:3306"
    sqlDatabase=rankup
    sqlPassword=MYPASSWORD
    sqlTablePrefix=rankup_
    sqlUsername=root
}

and this happened; https://cdn.discordapp.com/attachments/369719369577791489/434024794988478475/unknown.png

**Comment by Spontini** [comment]
Okay, i unistall everything then i installed Apache, MySQL and PHP also PHPMyAdmin then created a database named "rankup" with PHPMyAdmin as you can see in there;
![image](https://user-images.githubusercontent.com/35429381/38703924-50a57b4a-3ead-11e8-801c-d2674388980f.png)
Then i eddited my "Database" config like this;
}
databases {
    # You may choose between MySQL (Mariadb works too) or H2 (Hikari) databases for Player Stats storage!
    database=h2
    sqlAddress="localhost:3306"
    sqlDatabase=rankup
    sqlPassword= MyPassword
    sqlTablePrefix="rankup_"
    sqlUsername=root
}
but it still do not record the playing times, they stuck in 1, 2 minutes.

**Comment by Asherslab** [comment]
disable the module, you don't need database.

**Comment by Asherslab** [comment]
Solved via discord

**Comment by LGCMcLovin** [comment]
What was the fix? Having same issue while using MySQL
