### ISSUE TITLE
Says I'm already the highest group

### ISSUE THREAD

**Issue by Trentaxx** [Minecolonies/Rankup#23]
When I do /ru check It says I'm already the highest group but I'm set to default group In Lp
![17f67d3f4bb63febc6617cf236510756](https://user-images.githubusercontent.com/48046606/53472920-08659c80-3a37-11e9-9d44-473f24d6f85b.png)

**Comment by Asherslab** [comment]
then your configuration is invalid, a valid configuration will not produce this problem
