### ISSUE TITLE
needed on-the-go reload commands

### ISSUE THREAD

**Issue by Philosyang** [Minecolonies/Rankup#7]
server-type: Sponge 1.10.2 newest stable
It is too bad every time after I changed something in the rankup configurations, I needed to restart the server for the plugin to reload...
Hopefully can add some commands such as **/ru reload** or **/ru reload [filename]**, that would be very helpful!

**Comment by Asherslab** [comment]
if you use the standard /sponge plugins reload it will reload Most configs (Haven't checked them all, sorry)

**Comment by Bucky420** [comment]
if u want sponge to reload u have to hook the sponge reload event ... u dont do this .. so reload does not work

**Comment by Asherslab** [comment]
@codydbgt yes i do
https://github.com/ldtteam/Rankup/blob/111e8800a8ed12c36c0616da0d3b0b0f8ae540d0/src/main/java/com/minecolonies/rankup/Rankup.java#L161
