### ISSUE TITLE
{joindate} does not follow the date-format

### ISSUE THREAD

**Issue by Philosyang** [Minecolonies/Rankup#8]
only {lastjoin} has changed as the lastjoin. Please refer to the pic.
![image](https://user-images.githubusercontent.com/24841393/32492772-66453e86-c3f6-11e7-9349-cfbd7326737c.png)
![image](https://user-images.githubusercontent.com/24841393/32492788-73845f1e-c3f6-11e7-8b60-9045acd72ea5.png)

**Comment by Asherslab** [comment]
hmm, interesting. In the newest versions (Not merged yet) the format will not be an option anymore (Sorry, it was causing problems) BUT, the format will be "yyyy/MM/dd"

**Comment by Philosyang** [comment]
That’s okay, thanks for your awesome plugin!

**Comment by Asherslab** [comment]
Sure thing! btw feel free to join the discord:
https://discord.gg/bmARmpV
